import React, { useEffect, useState } from "react";
import { ActivityIndicator, KeyboardAvoidingView, Platform, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { requestPasswordReset, resetPassword, verifyPasswordReset } from "../services/api";
import AuthDialog from "../components/AuthDialog";
import OtpInput from "../components/OtpInput";
import colors, { radius, spacing } from "../constants/colors";
function friendlyError(error) { const code = error.response?.data?.errorCode; if (code === "RESET_OTP_EXPIRED") return "This code has expired. Request a new one."; if (code === "RESET_OTP_ATTEMPTS_EXCEEDED") return "Too many attempts. Request a new code."; if (code === "RESET_OTP_COOLDOWN") return "Please wait before requesting another code."; return error.response?.data?.message || "We couldn't complete that request. Please try again."; }
export default function ForgotPasswordScreen({ navigation, route }) { const [email, setEmail] = useState(route?.params?.email || ""); const [code, setCode] = useState(""); const [resetToken, setResetToken] = useState(""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [phase, setPhase] = useState("EMAIL"); const [busy, setBusy] = useState(false); const [cooldown, setCooldown] = useState(0); const [error, setError] = useState(""); const [dialog, setDialog] = useState(false);
  useEffect(() => { if (cooldown <= 0) return undefined; const timer = setInterval(() => setCooldown((value) => Math.max(0, value - 1)), 1000); return () => clearInterval(timer); }, [cooldown]);
  const send = async () => { if (!/^\S+@\S+\.\S+$/.test(email.trim())) { setError("Enter a valid email."); return; } setBusy(true); setError(""); try { await requestPasswordReset(email.trim().toLowerCase()); setPhase("CODE"); setCooldown(60); } catch (e) { setError(friendlyError(e)); } finally { setBusy(false); } };
  const verify = async () => { if (code.length !== 6) { setError("Enter the 6-digit code from your email."); return; } setBusy(true); setError(""); try { const result = await verifyPasswordReset(email.trim().toLowerCase(), code); setResetToken(result.resetToken); setPhase("PASSWORD"); } catch (e) { setError(friendlyError(e)); } finally { setBusy(false); } };
  const resend = async () => { if (cooldown > 0 || busy) return; setBusy(true); setError(""); try { await requestPasswordReset(email.trim().toLowerCase()); setCooldown(60); } catch (e) { setError(friendlyError(e)); } finally { setBusy(false); } };
  const reset = async () => { if (password.length < 8 || password !== confirm) { setError("Enter a password of at least 8 characters and matching confirmation."); return; } setBusy(true); setError(""); try { await resetPassword(resetToken, password, confirm); setDialog(true); } catch (e) { setError(friendlyError(e)); } finally { setBusy(false); } };
  const field = (label, value, setValue, props = {}) => <><Text style={styles.label}>{label}</Text><TextInput style={styles.input} placeholder={label} placeholderTextColor={colors.muted} value={value} onChangeText={setValue} {...props} /></>;
  return <SafeAreaView style={styles.flex} edges={["top", "bottom"]}><KeyboardAvoidingView style={styles.flex} behavior={Platform.OS === "ios" ? "padding" : "height"}><View style={styles.container}><TouchableOpacity onPress={() => phase === "EMAIL" ? navigation.navigate("Auth") : setPhase(phase === "PASSWORD" ? "CODE" : "EMAIL")}><Text style={styles.back}>‹ {phase === "EMAIL" ? "Back to sign in" : "Back"}</Text></TouchableOpacity><View style={styles.content}><Text style={styles.title}>{phase === "EMAIL" ? "Forgot password?" : phase === "CODE" ? "Verify reset code" : "Choose a new password"}</Text><Text style={styles.subtitle}>{phase === "EMAIL" ? "Enter your account email. We'll send a secure reset code if an account exists." : phase === "CODE" ? "Enter the 6-digit code sent to your email." : "Your reset code is verified. Set a new password to continue."}</Text>{phase === "EMAIL" ? <>{field("Email address", email, setEmail, { autoCapitalize: "none", keyboardType: "email-address" })}<TouchableOpacity style={[styles.button, busy && styles.disabled]} onPress={send} disabled={busy}>{busy ? <ActivityIndicator color={colors.white} /> : <Text style={styles.buttonText}>Send Code</Text>}</TouchableOpacity></> : phase === "CODE" ? <><Text style={styles.label}>Verification code</Text><OtpInput value={code} onChangeText={setCode} disabled={busy} accessibilityLabel="Password reset code" /><TouchableOpacity style={[styles.button, busy && styles.disabled]} onPress={verify} disabled={busy}>{busy ? <ActivityIndicator color={colors.white} /> : <Text style={styles.buttonText}>Verify Code</Text>}</TouchableOpacity><TouchableOpacity onPress={resend} disabled={cooldown > 0 || busy}><Text style={[styles.resend, cooldown > 0 && styles.muted]}>{cooldown > 0 ? `Resend code in 00:${String(cooldown).padStart(2, "0")}` : "Resend code"}</Text></TouchableOpacity></> : <><Text style={styles.label}>New password</Text><TextInput style={styles.input} placeholder="Password" placeholderTextColor={colors.muted} secureTextEntry value={password} onChangeText={setPassword} /><Text style={styles.label}>Confirm password</Text><TextInput style={styles.input} placeholder="Confirm password" placeholderTextColor={colors.muted} secureTextEntry value={confirm} onChangeText={setConfirm} /><TouchableOpacity style={[styles.button, busy && styles.disabled]} onPress={reset} disabled={busy}>{busy ? <ActivityIndicator color={colors.white} /> : <Text style={styles.buttonText}>Update Password</Text>}</TouchableOpacity></>}{error ? <Text style={styles.error}>{error}</Text> : null}</View></View></KeyboardAvoidingView><AuthDialog visible={dialog} title="Password updated" message="Your password has been changed. Sign in with your new password to continue." actionLabel="Go to Login" onAction={() => { setDialog(false); navigation.navigate("Auth", { email }); }} /></SafeAreaView>; }
const styles = StyleSheet.create({ flex: { flex: 1, backgroundColor: colors.background }, container: { flex: 1, padding: spacing.lg }, back: { color: colors.navy, fontSize: 16, fontWeight: "800" }, content: { flex: 1, justifyContent: "center" }, title: { color: colors.primary, fontSize: 28, fontWeight: "900" }, subtitle: { color: colors.muted, lineHeight: 21, marginVertical: spacing.md }, label: { color: colors.primary, fontSize: 13, fontWeight: "800", marginBottom: 6 }, input: { backgroundColor: colors.card, borderColor: colors.border, borderWidth: 1, borderRadius: radius.md, padding: 15, marginBottom: spacing.md, fontSize: 16, color: colors.primary }, button: { backgroundColor: colors.accent, borderRadius: radius.md, padding: 16, alignItems: "center", marginTop: spacing.sm }, disabled: { opacity: .6 }, buttonText: { color: colors.white, fontWeight: "800", fontSize: 16 }, resend: { color: colors.navy, textAlign: "center", fontWeight: "800", marginTop: spacing.lg }, muted: { color: colors.muted }, error: { color: colors.danger, marginTop: spacing.md, textAlign: "center" } });
