import React from "react";
import { ActivityIndicator, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import EmptyState from "../components/EmptyState";
import ErrorState from "../components/ErrorState";
import colors, { radius, shadow, spacing } from "../constants/colors";
import { getHistory } from "../services/api";
import { formatCurrency } from "../utils/formatCurrency";
import { PROVIDER_LAUNCH_CONFIG } from "../services/providerLauncher";

export default function HistoryDetailScreen({ route, navigation }) {
  const [entry, setEntry] = React.useState(null); const [error, setError] = React.useState(false);
  const load = React.useCallback(() => { setError(false); setEntry(null); getHistory(route.params?.historyId).then((res) => setEntry(res.data)).catch(() => setError(true)); }, [route.params?.historyId]);
  React.useEffect(() => { load(); }, [load]);
  if (error) return <View style={styles.flex}><ErrorState title="History unavailable" message="This comparison could not be loaded." onRetry={load} /></View>;
  if (!entry) return <View style={styles.loading}><ActivityIndicator color={colors.accent} /><Text style={styles.muted}>Loading comparison…</Text></View>;
  const compareAgain = () => navigation.navigate("MainTabs", { screen: "Home", params: { compareAgain: entry } });
  return <ScrollView style={styles.flex} contentContainerStyle={styles.content}><View style={styles.card}><Text style={styles.eyebrow}>Route</Text><Text style={styles.route}>{entry.pickup.label}</Text><Text style={styles.arrow}>↓</Text><Text style={styles.route}>{entry.destination.label}</Text><Text style={styles.date}>{new Date(entry.searchedAt).toLocaleString()}</Text><View style={styles.stats}><Text style={styles.stat}>{entry.route?.distanceMeters == null ? "Distance unavailable" : `${(entry.route.distanceMeters / 1000).toFixed(1)} km`}</Text><Text style={styles.stat}>{entry.route?.durationSeconds == null ? "Duration unavailable" : `~${Math.round(entry.route.durationSeconds / 60)} min`}</Text></View></View><Text style={styles.heading}>Historical quote snapshots</Text><Text style={styles.noteTop}>Fares shown here are from this previous comparison.</Text><View style={styles.card}>{entry.quotes.map((quote, index) => <View style={[styles.quote, index > 0 && styles.divider]} key={`${quote.provider}-${index}`}><View style={styles.quoteCopy}><Text style={styles.provider}>{PROVIDER_LAUNCH_CONFIG[quote.provider]?.label || quote.provider}</Text><Text style={styles.muted}>{quote.category || "Category unavailable"} · {quote.availability || "Availability unavailable"}</Text></View><Text style={styles.fare}>{quote.fare == null ? "Unavailable" : formatCurrency(quote.fare)}</Text></View>)}</View><TouchableOpacity style={styles.button} onPress={compareAgain}><Text style={styles.buttonText}>Compare Again</Text></TouchableOpacity><Text style={styles.note}>Compare Again performs a fresh fare comparison; these historical quotes are not reused.</Text></ScrollView>;
}
const styles = StyleSheet.create({ flex: { flex: 1, backgroundColor: colors.background }, loading: { flex: 1, alignItems: "center", justifyContent: "center", gap: spacing.sm, backgroundColor: colors.background }, content: { padding: spacing.lg }, card: { backgroundColor: colors.card, borderRadius: radius.lg, padding: spacing.lg, marginBottom: spacing.md, ...shadow }, eyebrow: { color: colors.forest, fontWeight: "800", fontSize: 12, textTransform: "uppercase", letterSpacing: 1, marginBottom: spacing.sm }, route: { fontSize: 17, fontWeight: "800", color: colors.primary }, arrow: { color: colors.accent, fontSize: 18, marginVertical: 2 }, date: { color: colors.muted, marginTop: spacing.md, fontSize: 12 }, stats: { flexDirection: "row", gap: spacing.lg, marginTop: spacing.md }, stat: { color: colors.primary, fontWeight: "700" }, heading: { color: colors.primary, fontWeight: "800", fontSize: 17, marginTop: spacing.sm }, noteTop: { color: colors.muted, fontSize: 12, marginTop: 5, marginBottom: spacing.sm }, quote: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingVertical: spacing.sm }, divider: { borderTopWidth: 1, borderTopColor: colors.border }, quoteCopy: { flex: 1 }, provider: { color: colors.primary, fontWeight: "800" }, muted: { color: colors.muted, fontSize: 12 }, fare: { color: colors.primary, fontWeight: "800", fontSize: 16 }, button: { backgroundColor: colors.accent, borderRadius: radius.md, alignItems: "center", paddingVertical: 15, marginTop: spacing.sm }, buttonText: { color: colors.white, fontWeight: "800" }, note: { color: colors.muted, textAlign: "center", fontSize: 12, lineHeight: 17, marginTop: spacing.md } });
