import React from "react";
import { ActivityIndicator, Alert, FlatList, Modal, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import AppHeader from "../components/AppHeader";
import EmptyState from "../components/EmptyState";
import ErrorState from "../components/ErrorState";
import PrimaryButton from "../components/PrimaryButton";
import SavedTripMenu from "../components/SavedTripMenu";
import colors, { radius, shadow, spacing } from "../constants/colors";
import { deleteSavedRoute, getSavedRoutes, updateSavedRoute } from "../services/api";

const LABELS = ["HOME", "WORK", "UNIVERSITY", "FAVORITE", "CUSTOM"];
const LABEL_TEXT = { HOME: "Home", WORK: "Work", UNIVERSITY: "University", FAVORITE: "Favorite", CUSTOM: "Custom" };

function EditModal({ routeItem, onClose, onSaved }) {
  const [name, setName] = React.useState(routeItem?.name || ""); const [labelType, setLabelType] = React.useState(routeItem?.labelType || "FAVORITE"); const [saving, setSaving] = React.useState(false);
  const save = async () => { if (!name.trim() || saving) return; setSaving(true); try { await updateSavedRoute(routeItem.id, { name: name.trim(), labelType }); onSaved(); } catch { Alert.alert("Unable to update", "Please try again."); } finally { setSaving(false); } };
  return <Modal transparent animationType="slide" visible onRequestClose={onClose}><View style={styles.modalBackdrop}><View style={styles.modalCard}><Text style={styles.modalTitle}>Edit Saved Trip</Text><Text style={styles.fieldLabel}>Name</Text><TextInput value={name} onChangeText={setName} maxLength={100} style={styles.textInput} placeholder="Home to University" /><Text style={styles.fieldLabel}>Label</Text><View style={styles.labelRow}>{LABELS.map((label) => <TouchableOpacity key={label} onPress={() => setLabelType(label)} style={[styles.labelChip, labelType === label && styles.labelChipActive]}><Text style={[styles.labelText, labelType === label && styles.labelTextActive]}>{LABEL_TEXT[label]}</Text></TouchableOpacity>)}</View><PrimaryButton title="Save Changes" onPress={save} loading={saving} disabled={!name.trim() || saving} /><TouchableOpacity onPress={onClose} disabled={saving} style={styles.cancelButton}><Text style={styles.cancelText}>Cancel</Text></TouchableOpacity></View></View></Modal>;
}

export default function SavedRoutesScreen({ navigation }) {
  const [items, setItems] = React.useState([]); const [loading, setLoading] = React.useState(true); const [error, setError] = React.useState(null); const [editing, setEditing] = React.useState(null); const [menuItem, setMenuItem] = React.useState(null); const [menuAnchor, setMenuAnchor] = React.useState(null);
  const load = React.useCallback(async () => { setLoading(true); try { setItems((await getSavedRoutes()).data || []); setError(null); } catch { setError("Couldn't load saved trips."); } finally { setLoading(false); } }, []);
  React.useEffect(() => { load(); }, [load]);
  const compare = (item) => navigation.navigate("MainTabs", { screen: "Home", params: { savedRoute: item } });
  const remove = (item) => { setMenuItem(null); setMenuAnchor(null); Alert.alert(`Delete "${item.name}"?`, "This removes the saved shortcut only. Your comparison history will remain unchanged.", [{ text: "Cancel", style: "cancel" }, { text: "Delete", style: "destructive", onPress: async () => { try { await deleteSavedRoute(item.id); setItems((current) => current.filter((saved) => saved.id !== item.id)); } catch { Alert.alert("Unable to delete", "Please try again."); } } }]); };
  if (error) return <View style={styles.flex}><AppHeader title="Saved Trips" subtitle="Quickly compare your regular routes" showLogo={false} /><ErrorState title="Saved trips unavailable" message={error} onRetry={load} /></View>;
  if (loading && !items.length) return <View style={styles.flex}><AppHeader title="Saved Trips" subtitle="Quickly compare your regular routes" showLogo={false} /><View style={styles.loading}><ActivityIndicator color={colors.accent} /><Text style={styles.muted}>Loading saved trips…</Text></View></View>;
  return <View style={styles.flex}><AppHeader title="Saved Trips" subtitle="Quickly compare your regular routes" showLogo={false} />{!items.length ? <EmptyState title="No saved trips yet" message="Save routes you travel often for quicker fare comparisons." /> : <FlatList data={items} keyExtractor={(item) => String(item.id)} contentContainerStyle={styles.content} refreshing={loading} onRefresh={load} renderItem={({ item }) => <View style={styles.card}><View style={styles.cardTop}><View style={styles.titleWrap}><Text style={styles.routeName}>{item.name}</Text><Text style={styles.label}>{LABEL_TEXT[item.labelType] || item.labelType}</Text></View><TouchableOpacity accessibilityLabel="Saved trip menu" onPress={(event) => { setMenuItem(item); setMenuAnchor(event.nativeEvent); }} style={styles.menuButton}><Text style={styles.menuGlyph}>⋮</Text></TouchableOpacity></View><Text style={styles.location}>{item.pickup.name}</Text><Text style={styles.arrow}>→</Text><Text style={styles.location}>{item.destination.name}</Text><TouchableOpacity style={styles.compareButton} onPress={() => compare(item)} accessibilityLabel="Compare saved trip"><Text style={styles.compareText}>Compare</Text></TouchableOpacity></View>} />}{editing && <EditModal routeItem={editing} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); load(); }} />}<SavedTripMenu item={menuItem} anchor={menuAnchor} onClose={() => { setMenuItem(null); setMenuAnchor(null); }} onEdit={() => { const target = menuItem; setMenuItem(null); setMenuAnchor(null); setEditing(target); }} onDelete={() => remove(menuItem)} /></View>;
}

const styles = StyleSheet.create({ flex: { flex: 1, backgroundColor: colors.background }, content: { padding: spacing.lg, paddingTop: spacing.sm }, loading: { flex: 1, justifyContent: "center", alignItems: "center", gap: spacing.sm }, muted: { color: colors.muted }, card: { backgroundColor: colors.card, borderRadius: radius.lg, padding: spacing.md, marginBottom: spacing.md, ...shadow }, cardTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" }, titleWrap: { flex: 1 }, routeName: { fontSize: 17, fontWeight: "800", color: colors.primary }, label: { color: colors.forest, fontSize: 11, fontWeight: "800", marginTop: 4, textTransform: "uppercase", letterSpacing: 0.5 }, menuButton: { width: 42, height: 42, alignItems: "center", justifyContent: "center" }, menuGlyph: { color: colors.muted, fontSize: 24 }, location: { fontSize: 14, color: colors.primary, fontWeight: "600", marginTop: spacing.md }, arrow: { color: colors.accent, fontSize: 18, marginTop: 2 }, compareButton: { backgroundColor: colors.accent, borderRadius: radius.md, paddingVertical: 12, alignItems: "center", marginTop: spacing.lg }, compareText: { color: colors.white, fontWeight: "800" }, modalBackdrop: { flex: 1, backgroundColor: "rgba(15,23,42,.45)", justifyContent: "flex-end" }, modalCard: { backgroundColor: colors.card, borderTopLeftRadius: radius.lg, borderTopRightRadius: radius.lg, padding: spacing.lg }, modalTitle: { fontSize: 20, fontWeight: "800", color: colors.primary, marginBottom: spacing.lg }, fieldLabel: { color: colors.muted, fontSize: 12, fontWeight: "700", marginBottom: spacing.sm }, textInput: { borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, padding: 12, marginBottom: spacing.lg, color: colors.primary }, labelRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: spacing.lg }, labelChip: { borderWidth: 1, borderColor: colors.border, borderRadius: 999, paddingHorizontal: 12, paddingVertical: 8 }, labelChipActive: { backgroundColor: colors.forest, borderColor: colors.forest }, labelText: { color: colors.muted, fontWeight: "700", fontSize: 12 }, labelTextActive: { color: colors.white }, cancelButton: { alignItems: "center", padding: spacing.md }, cancelText: { color: colors.muted, fontWeight: "700" } });
