import React, { useEffect, useRef } from "react";
import { Animated, FlatList, Modal, Text, TouchableOpacity, View, StyleSheet } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import LogoMark from "../LogoMark";
import colors, { radius, shadow, spacing } from "../../constants/colors";
import AIConversationRow from "./AIConversationRow";

export default function AIConversationDrawer({ visible, conversations, activeId, deletingId, editingId, editText, editError, renameSaving, loading, onClose, onNewChat, onSelect, onMenu, onEditText, onSaveRename, onCancelRename, onRetry }) {
  const insets = useSafeAreaInsets(); const slide = useRef(new Animated.Value(-390)).current;
  useEffect(() => { if (visible) Animated.timing(slide, { toValue: 0, duration: 230, useNativeDriver: true }).start(); }, [visible, slide]);
  if (!visible) return null;
  const pinned = conversations.filter((item) => item.isPinned); const recent = conversations.filter((item) => !item.isPinned);
  const data = [{ type: "brand" }, { type: "new" }, { type: "heading" }, ...(pinned.length ? [{ type: "section", title: "Pinned" }] : []), ...pinned.map((item) => ({ type: "conversation", item })), ...(recent.length ? [{ type: "section", title: "Recent" }] : []), ...recent.map((item) => ({ type: "conversation", item }))];
  return <Modal transparent visible animationType="none" onRequestClose={onClose}><View style={styles.overlay}><TouchableOpacity accessibilityLabel="Close drawer" style={styles.scrim} activeOpacity={1} onPress={onClose} /><Animated.View style={[styles.drawer, { transform: [{ translateX: slide }], paddingTop: insets.top + 12, paddingBottom: insets.bottom + 12 }]}><FlatList data={data} keyExtractor={(item, index) => item.item ? `conversation-${item.item.id}` : `${item.type}-${index}`} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false} renderItem={({ item }) => {
    if (item.type === "brand") return <View style={styles.brand}><LogoMark size={38} /><View><Text style={styles.brandName}>Fair Fare</Text><Text style={styles.brandSub}>Ride smarter, together.</Text></View><TouchableOpacity accessibilityLabel="Close drawer" onPress={onClose} style={styles.close}><Text style={styles.closeIcon}>×</Text></TouchableOpacity></View>;
    if (item.type === "new") return <TouchableOpacity accessibilityLabel="New chat" onPress={onNewChat} style={styles.newChat}><Text style={styles.newIcon}>＋</Text><Text style={styles.newText}>New Chat</Text></TouchableOpacity>;
    if (item.type === "heading") return <Text style={styles.heading}>AI Conversations</Text>;
    if (item.type === "section") return <Text style={styles.section}>{item.title}</Text>;
    return <AIConversationRow conversation={item.item} selected={activeId === item.item.id} deleting={deletingId === item.item.id} editing={editingId === item.item.id} editText={editText} editError={editError} saving={renameSaving} onEditText={onEditText} onSave={onSaveRename} onCancel={onCancelRename} onPress={() => onSelect(item.item.id)} onMenu={onMenu} />;
  }} ListFooterComponent={loading ? <Text style={styles.status}>Loading conversations…</Text> : conversations.length === 0 ? <View><Text style={styles.status}>No saved conversations yet.</Text><TouchableOpacity onPress={onRetry}><Text style={styles.retry}>Try again</Text></TouchableOpacity></View> : null} /></Animated.View></View></Modal>;
}
const styles = StyleSheet.create({ overlay: { flex: 1, flexDirection: "row" }, scrim: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(15, 23, 42, .42)" }, drawer: { width: "86%", maxWidth: 390, backgroundColor: colors.background, ...shadow }, content: { paddingHorizontal: spacing.md, paddingBottom: spacing.lg }, brand: { minHeight: 58, flexDirection: "row", alignItems: "center", marginBottom: spacing.lg }, brandName: { color: colors.forest, fontSize: 18, fontWeight: "900", marginLeft: 10 }, brandSub: { color: colors.muted, fontSize: 11, marginLeft: 10, marginTop: 2 }, close: { marginLeft: "auto", width: 42, height: 42, alignItems: "center", justifyContent: "center" }, closeIcon: { fontSize: 28, color: colors.muted }, newChat: { height: 52, borderRadius: radius.md, backgroundColor: colors.forest, flexDirection: "row", alignItems: "center", paddingHorizontal: spacing.md, marginBottom: spacing.lg }, newIcon: { color: colors.white, fontSize: 24, marginRight: 9 }, newText: { color: colors.white, fontSize: 15, fontWeight: "800" }, heading: { color: colors.primary, fontSize: 14, fontWeight: "800", marginBottom: spacing.sm }, section: { color: colors.muted, textTransform: "uppercase", fontSize: 11, letterSpacing: 1, fontWeight: "800", marginTop: spacing.md, marginBottom: spacing.sm }, status: { color: colors.muted, textAlign: "center", paddingVertical: spacing.lg }, retry: { color: colors.forest, fontWeight: "800", textAlign: "center" } });
