import React from "react";
import { Platform, Share, Text, TouchableOpacity, View, StyleSheet } from "react-native";
import LogoMark from "../LogoMark";
import colors, { radius, spacing } from "../../constants/colors";
function inlineParts(text) { return String(text).split(/(\*\*[^*]+\*\*|__[^_]+__|\*[^*]+\*|_[^_]+_)/g).filter(Boolean).map((part, index) => { const bold = /^\*\*|^__/.test(part); const italic = !bold && (/^\*|^_/.test(part)); return <Text key={`${part}-${index}`} style={[bold && styles.bold, italic && styles.italic]}>{part.replace(/^\*\*|\*\*$|^__|__$|^\*|\*$|^_|_$/g, "")}</Text>; }); }
function Markdown({ content, user }) { const lines = String(content || "").split(/\r?\n/); const output = []; let list = []; const flush = () => { if (list.length) { output.push(<View key={`list-${output.length}`} style={styles.list}>{list.map((line, i) => <View key={`${line.text}-${i}`} style={styles.listRow}><Text style={styles.bullet}>{line.ordered ? `${i + 1}.` : "•"}</Text><Text style={[styles.body, user && styles.userText]}>{inlineParts(line.text)}</Text></View>)}</View>); list = []; } }; lines.forEach((line, index) => { const match = line.match(/^\s*(?:[-*•]|(\d+)[.)])\s+(.*)$/); if (match) { list.push({ text: match[2], ordered: Boolean(match[1]) }); return; } flush(); if (!line.trim()) output.push(<View key={`space-${index}`} style={styles.space} />); else output.push(<Text key={`line-${index}`} style={[styles.body, user && styles.userText]}>{inlineParts(line)}</Text>); }); flush(); return <View>{output}</View>; }
async function copyText(text) { if (Platform.OS === "web" && globalThis.navigator?.clipboard) return globalThis.navigator.clipboard.writeText(String(text)); return Share.share({ message: String(text) }); }
export default function AIMessageBubble({ message, onRetry }) { const user = message.role === "USER"; return <View style={[styles.messageRow, user && styles.userRow]}>{!user ? <LogoMark size={26} style={styles.avatar} /> : null}<View style={[styles.column, user && styles.userColumn]}><View style={[styles.bubble, user ? styles.userBubble : styles.assistantBubble]}><Markdown content={message.content} user={user} /></View><View style={[styles.meta, user && styles.userMeta]}><Text style={styles.time}>{message.createdAt ? new Date(message.createdAt).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" }) : ""}</Text>{message.failed ? <><Text style={styles.failed}>Unable to get a response right now.</Text>{onRetry ? <TouchableOpacity accessibilityLabel="Retry message" onPress={onRetry}><Text style={styles.action}>Retry</Text></TouchableOpacity> : null}</> : !user ? <TouchableOpacity accessibilityLabel="Copy message" onPress={() => copyText(message.content)}><Text style={styles.action}>Copy</Text></TouchableOpacity> : null}</View></View></View>; }
const styles = StyleSheet.create({ messageRow: { flexDirection: "row", alignItems: "flex-end", marginBottom: 14, paddingHorizontal: spacing.md }, userRow: { justifyContent: "flex-end" }, avatar: { marginRight: 8, marginBottom: 20 }, column: { maxWidth: "86%" }, userColumn: { alignItems: "flex-end", maxWidth: "82%" }, bubble: { paddingHorizontal: 14, paddingVertical: 10, borderRadius: radius.lg }, userBubble: { backgroundColor: colors.forest, borderBottomRightRadius: 6 }, assistantBubble: { backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, borderBottomLeftRadius: 6 }, body: { color: colors.primary, fontSize: 15, lineHeight: 21 }, userText: { color: colors.white }, bold: { fontWeight: "800" }, italic: { fontStyle: "italic" }, list: { marginTop: 1 }, listRow: { flexDirection: "row", paddingLeft: 1, marginBottom: 4 }, bullet: { color: colors.accent, width: 21, fontWeight: "800" }, space: { height: 5 }, meta: { flexDirection: "row", alignItems: "center", marginTop: 4, paddingHorizontal: 3, flexWrap: "wrap" }, userMeta: { justifyContent: "flex-end" }, time: { color: colors.muted, fontSize: 10 }, failed: { color: colors.danger, fontSize: 11, marginLeft: 8 }, action: { color: colors.forest, fontSize: 11, fontWeight: "800", marginLeft: 12, paddingVertical: 4 } });
